version: '3'
services:
  jupyter-pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-pyspark
    ports:
      - "8888:8888"
    volumes:
      - ../../:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_OPTS="--driver-java-options=-Xms1024M --driver-java-options=-Xmx4096M --driver-java-options=-Dlog4j.logLevel=info"
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' 